let guestList = ["Mudassir","Fatima","Maryam","Sania","Manahil"];
let guestwhoarenotComing = guestList[0];
console.log(guestwhoarenotComing, "I cant join");
guestList.splice(0, 1, "Zayd");
console.log("YAY! I HAVE FOUND A BIGGER TABLE FOR DINNER");
guestList.unshift("Fareena");
guestList.push("Ayyan");
let middleIndex: number = Math.floor(guestList.length / 2);
guestList.splice(middleIndex, 0, "Rayma");
console.log("Updated List Of Guest");
guestList.forEach(oneguest => console.log(`Hello ${oneguest}, Would you like to have dinner with me?`));
