var guestList = ["Mudassir", "Fatima", "Maryam", "Sania", "Manahil"];
var guestwhoarenotComing = guestList[0];
console.log(guestwhoarenotComing, "I cant join");
guestList.splice(0, 1, "Zayd");
console.log("YAY! I HAVE FOUND A BIGGER TABLE FOR DINNER");
guestList.unshift("Fareena");
guestList.push("Ayyan");
var middleIndex = Math.floor(guestList.length / 2);
guestList.splice(middleIndex, 0, "Rayma");
console.log("Updated List Of Guest");
guestList.forEach(function (oneguest) { return console.log("Hello ".concat(oneguest, ", Would you like to have dinner with me?")); });
